title: The Rooted Wisdom
description: A living herbal school rooted in spirit, ancestors, and earth.
url: https://therootedwisdom.com
author: Dara Pressley
email: hello@therootedwisdom.com
buildYear: 2026

social:
  instagram:
    url: https://www.instagram.com/therootedwisdomherbal/
    handle: "@therootedwisdomherbal"
  tiktok:
    url: https://www.tiktok.com/@mytrinisoul
    handle: "@mytrinisoul"
  fanbase:
    url: https://fanbase.app/therootedwisdom
    handle: "@therootedwisdom"
